### ISSUE TITLE
Beacon

### ISSUE THREAD

**Issue by rmachavariani** [davincisatellite/msp-flightsoftware#26]
# To-do

- [ ] Make a standard beacon for position etc
- [ ] Make sure that the beacon can be disabled if necessary 

# Notes

- Figure out what the transceiver can do as a beacon

# Testing
- [ ] Make a standard beacon for position etc
- [ ] Make sure that the beacon can be disabled if necessary 

@LiamC-00 @MauritsKuipers will supervise testing on campus
