### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by rmachavariani** [davincisatellite/msp-flightsoftware#27]
# To-do

- [ ] Message receive frame
- [ ] Message send frame
- [ ] Ping command

# Testing

- [ ] Receive message and read on buffer
- [ ] Transmit message and read on target
- [ ] Transmit ping command and read on OB

@LiamC-00 @MauritsKuipers will supervise testing on campus
