### ISSUE TITLE
Buffer management

### ISSUE THREAD

**Issue by rmachavariani** [davincisatellite/msp-flightsoftware#28]
# Update

This might be implemented in MCU side and not Antenna.

# To-do

- [ ] Remove message from buffer
- [ ] Send to buffer
- [ ] Retrieve buffer status (full, empty etc.)

# Testing

- [ ] Fill the buffer
- [ ] Ask for status
- [ ] Remove message from buffer, verify status

@LiamC-00 @MauritsKuipers will supervise testing on campus
