### ISSUE TITLE
Operational modes

### ISSUE THREAD

**Issue by rmachavariani** [davincisatellite/msp-flightsoftware#29]
# To-do

- [ ] Reboot counter (Systems' team requirement)
- [ ] Check battery voltage 
- [ ] Health check: EPS
- [ ] Health check: ADCS
- [ ] Health check: Antenna
- [ ] Health check: Dice payload
- [ ] Health check: Bitflip
- [ ] Health check: Temperature sensors (?)
- [ ] Health check: Hyperion OBC (?)

# Notes

# Testing

- [ ] Receive all the healthchecks
