### ISSUE TITLE
Bootloader

### ISSUE THREAD

**Issue by rmachavariani** [davincisatellite/msp-flightsoftware#30]
# To-do

- [ ]  Partitioning (ask Speretta <3)
- [ ]  Implement 0AB bootloader

# Notes

# Testing

- [ ] Booting
- [ ] Ask Speretta how to test partitioning
