### ISSUE TITLE
EPS driver

### ISSUE THREAD

**Issue by Dennisman219** [davincisatellite/msp-flightsoftware#5]
# To-Do

ICD: `WD:361C/EPS Software ICD IVID 6 v1.2.pdf`

To implement the following commands:

- [x] Watchdog (ICD page 39)
- [x] Output bus group ON (ICD page 40)
- [x] Output bus group OFF (ICD page 41)
- [x] Output bus group STATE (ICD page 42)
- [x] Output bus channel OFF (ICD page 43)
- [x] Output bus channel ON (ICD page 44)
- [x] Switch to nominal mode (ICD page 45)
- [x] Switch to safety mode (ICD page 46)
- [x] Get system status (ICD page 47)
- [x] Get PDU/PIU overcurrent fault state (ICD page 49)
- [x] Reset configuration
- [x] #35
- [x] #32
- [x] #37
- [x] Get configuration parameter
- [x] #47  
- [x] Get PCU housekeeping data (ENG)
- [x] Get PCU housekeeping data (raw)
- [x] #49 
- [x] #53 
- [x] Get PBU housekeeping data (raw) (ICD page 59)
- [x] #53 
- [x] #53 
- [x] #53 
- [x] #53 

# Testing

At the same time as applying the code, it must be tested:

- [ ] Watchdog (ICD page 39)
- [ ] Output bus group ON (ICD page 40)
- [ ] Output bus group OFF (ICD page 41)
- [ ] Output bus group STATE (ICD page 42)
- [ ] Output bus channel OFF (ICD page 43)
- [ ] Output bus channel ON (ICD page 44)
- [ ] Switch to nominal mode (ICD page 45)
- [ ] Switch to safety mode (ICD page 46)
- [ ] Get system status (ICD page 47)
- [ ] Get PDU/PIU overcurrent fault state (ICD page 49)
- [ ] Reset configuration
- [ ] Configure EPS parameters (ICD page 77)
- [ ] Reset configuration parameter
- [ ] Set configuration parameter 
- [ ] Get configuration parameter
- [ ] Get PCU housekeeping data (rolling average)
- [ ] Get PCU housekeeping data (ENG)
- [ ] Get PCU housekeeping data (raw)
- [ ] Get PBU housekeeping data (rolling average)
- [ ] Get PBU housekeeping data (ENG) (ICD page 61)
- [ ] Get PBU housekeeping data (raw) (ICD page 59)
- [ ] Get PDU housekeeping data (rolling average) (ICD page 58)
- [ ] Get PDU housekeeping data (ENG) (ICD page 56)
- [ ] Get PDU housekeeping data (raw) (ICD page 53)
- [ ] Get PDU/ABF placed state (ICD page 51)

**Comment by Dennisman219** [comment]
Currently reviewing existing driver code before expanding
#33
